common: &common
:styles:
:thumb: "50x50#"
:small: "80x80#"
:medium: "200x150#"
:normal: "320x240#"
:large: "800x600#"
:default_url: "/images/default_image.png"


development:
<<: *common

production:
<<: *common
:storage: :s3
:bucket: "your-bucket-name"
:path: "/:some/:path/:id"
:url: "s3_domain_url

test:
<<: *common
